# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "nypl-collections"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Emma Spencer"]
  s.date = "2013-12-12"
  s.description = "A gem for interacting with the NYPL Digital Collections API"
  s.email = "emma.n.spencer@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "coverage/.last_run.json",
    "coverage/.resultset.json",
    "coverage/assets/0.8.0/application.css",
    "coverage/assets/0.8.0/application.js",
    "coverage/assets/0.8.0/colorbox/border.png",
    "coverage/assets/0.8.0/colorbox/controls.png",
    "coverage/assets/0.8.0/colorbox/loading.gif",
    "coverage/assets/0.8.0/colorbox/loading_background.png",
    "coverage/assets/0.8.0/favicon_green.png",
    "coverage/assets/0.8.0/favicon_red.png",
    "coverage/assets/0.8.0/favicon_yellow.png",
    "coverage/assets/0.8.0/loading.gif",
    "coverage/assets/0.8.0/magnify.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_flat_75_ffffff_40x100.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_glass_65_ffffff_1x400.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_glass_75_dadada_1x400.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png",
    "coverage/assets/0.8.0/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png",
    "coverage/assets/0.8.0/smoothness/images/ui-icons_222222_256x240.png",
    "coverage/assets/0.8.0/smoothness/images/ui-icons_2e83ff_256x240.png",
    "coverage/assets/0.8.0/smoothness/images/ui-icons_454545_256x240.png",
    "coverage/assets/0.8.0/smoothness/images/ui-icons_888888_256x240.png",
    "coverage/assets/0.8.0/smoothness/images/ui-icons_cd0a0a_256x240.png",
    "coverage/index.html",
    "lib/nypl_collections.rb",
    "lib/nypl_collections/client.rb",
    "lib/nypl_collections/configuration.rb",
    "spec/fixtures/return_captures_for_uuid.json",
    "spec/nypl_collections/client_spec.rb",
    "spec/nypl_collections/configuration_spec.rb",
    "spec/nypl_collections_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/enspencer/nypl-collections"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.6"
  s.summary = "A gem for interacting with the NYPL Digital Collections API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<dotenv>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<dotenv>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<dotenv>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

